import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

ColumnLayout {
    id: root
    
    property string fieldKey: ""
    property string label: ""
    property bool isRequired: false
    property string placeholderText: ""
    property var value: ""
    property bool isViewOnly: false
    property string errorText: ""

    signal inputValueChanged(string key, var val)

    Layout.fillWidth: true
    spacing: 6

    Text {
        text: root.label + (root.isRequired ? " <font color='#E53935'>*</font>" : "")
        textFormat: Text.RichText
        font.pixelSize: 13
        font.family: appTheme.inclusiveSansFontName
        color: "#333333"
    }

    TextField {
        id: field
        Layout.fillWidth: true
        Layout.preferredHeight: 30
        
        // Displays custom placeholder (e.g., "Autogenerated ID") when view-only instead of overriding with "N/A"
        placeholderText: root.isViewOnly ? (root.placeholderText !== "" ? root.placeholderText : "N/A") : root.placeholderText
        
        leftPadding: 12
        rightPadding: 32
        font.pixelSize: 12
        font.family: appTheme.rethinkSansFontName

        readOnly: root.isViewOnly
        color: root.isViewOnly ? "#666666" : "#333333"
        placeholderTextColor: "#AAAAAA"

        inputMethodHints: Qt.ImhDigitsOnly
        validator: RegularExpressionValidator { 
            regularExpression: /^-?\d+$/
        }

        text: root.value !== undefined ? root.value : ""
        onTextEdited: root.inputValueChanged(root.fieldKey, text)

        background: Rectangle {
            radius: 15
            color: root.isViewOnly ? "#EEEEEE" : "transparent"
            
            border {
                color: root.isViewOnly ? "transparent" : (root.errorText !== "" ? "#E53935" : (field.activeFocus ? appTheme.activeColor : "#888888"))
                width: field.activeFocus && !root.isViewOnly ? 2 : (root.isViewOnly ? 0 : 0.75)
            }
        }

        HoverHandler { 
            id: hover
        }

        transform: Translate {
            y: (hover.hovered && !root.isViewOnly) ? -2 : 0
            Behavior on y { 
                NumberAnimation { 
                    duration: 150
                    easing.type: Easing.OutQuad
                } 
            } 
        }

        Rectangle {
            visible: !root.isViewOnly && field.text !== ""
            width: 20
            height: 20
            radius: 10
            anchors.right: parent.right
            anchors.rightMargin: 8
            anchors.verticalCenter: parent.verticalCenter
            color: clearMouseArea.containsMouse ? "#E5E7EB" : "transparent"
            
            Image { 
                anchors.centerIn: parent
                source: "../../../../../assets/icons/close.svg"
                sourceSize: Qt.size(12, 12)
                opacity: 1.0
            }
            
            MouseArea {
                id: clearMouseArea
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                
                onClicked: {
                    field.text = ""
                    root.inputValueChanged(root.fieldKey, "")
                }
            }
        }
    }

    Text {
        visible: root.errorText !== ""
        text: root.errorText
        color: "#E53935"
        font.pixelSize: 11
        font.family: appTheme.rethinkSansFontName
        wrapMode: Text.WordWrap
        Layout.fillWidth: true
    }
}