from dataclasses import dataclass, asdict
from enum import Enum
from typing import Optional, List, Dict, Any

UNIT_STATUS_OPTIONS              = ['Available', 'Rented', 'Maintenance']
UNIT_STATUS_OPTIONS_EDITABLE     = ['Available', 'Maintenance']  # 'Rented' is system-managed
CUSTOMER_STATUS_OPTIONS          = ['Active', 'Blacklisted']
RENT_STATUS_OPTIONS              = ['Ongoing', 'Closed']
LIABILITY_STATUS_OPTIONS         = ['Pending', 'Settled']

class FieldType(Enum):
    TEXT     = 'text'
    REAL     = 'real'
    INT      = 'int'
    DATE     = 'date'
    DATETIME = 'datetime'
    FILE     = 'file'
    SELECT   = 'select'

@dataclass(frozen=True)
class FieldInfo:
    internal_name:    str
    display_name:     str
    type:             FieldType
    required:         bool = True
    is_primary_key:   bool = False
    is_foreign_key:   bool = False
    placeholder:      Optional[str] = None
    options:          Optional[List[str]] = None
    max_length:       Optional[int] = None
    dynamic_source:   Optional[str] = None   # live dropdown source key
    editable_in_add:  bool = True            # show/allow input in Add dialog
    editable_in_edit: bool = True            # show/allow input in Edit dialog
    auto_fill:        Optional[str] = None   # 'today' | 'now' — pre-fills the field on open

    def to_dict(self) -> Dict[str, Any]:
        data = {
            'key':              self.internal_name,
            'label':            self.display_name,
            'type':             self.type.value,
            'required':         self.required,
            'is_primary_key':   self.is_primary_key,
            'is_foreign_key':   self.is_foreign_key,
            'editable_in_add':  self.editable_in_add,
            'editable_in_edit': self.editable_in_edit,
        }
        if self.placeholder is not None:
            data['placeholder'] = self.placeholder
        if self.options is not None:
            data['options'] = self.options
        if self.max_length is not None:
            data['max_length'] = self.max_length
        if self.dynamic_source is not None:
            data['dynamic_source'] = self.dynamic_source
        if self.auto_fill is not None:
            data['auto_fill'] = self.auto_fill
        return data


# ---------------------------------------------------------------------------
# Units
# ---------------------------------------------------------------------------
class UnitField(Enum):
    UNIT_ID = FieldInfo(
        'unitID', 'ID',
        type=FieldType.INT,
        required=True,
        is_primary_key=True,
        placeholder='Autogenerated ID'
    )
    PLATE_NUMBER = FieldInfo(
        'plateNumber', 'Plate Number',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. ABC123',
        max_length=15,
    )
    UNIT_BRAND = FieldInfo(
        'unitBrand', 'Brand',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. Honda',
        max_length=30,
    )
    UNIT_MODEL = FieldInfo(
        'unitModel', 'Model',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. Click 125i',
        max_length=50,
    )
    UNIT_COLOR = FieldInfo(
        'unitColor', 'Color',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. Red',
        max_length=30,
    )
    UNIT_YEAR = FieldInfo(
        'unitYear', 'Year',
        type=FieldType.INT,
        required=True,
        placeholder='e.g. 2024',
    )
    UNIT_PICTURE = FieldInfo(
        'unitPicture', 'Picture',
        type=FieldType.FILE,
        required=False,
        max_length=255,
    )
    UNIT_STATUS = FieldInfo(
        'unitStatus', 'Status',
        type=FieldType.SELECT,
        required=True,
        options=UNIT_STATUS_OPTIONS,
        editable_in_add=False,   # defaults to 'Available' on insert — system sets it
        editable_in_edit=True,   # editable unless current status == 'Rented' (enforced in QML/controller)
        dynamic_source='unitStatusOptions'
    )
    DAILY_RATE = FieldInfo(
        'dailyRate', 'Daily Rate (₱)',
        type=FieldType.REAL,
        required=True,
        placeholder='e.g. 300.0',
    )
    DATE_ADDED = FieldInfo(
        'dateAdded', 'Date Added',
        type=FieldType.DATE,
        required=True,
        placeholder='YYYY-MM-DD',
        auto_fill='today',
    )

    @staticmethod
    def from_internal_name(name: str) -> 'UnitField':
        for field in UnitField:
            if field.value.internal_name == name:
                return field
        raise ValueError(f'Unknown field: {name}')

    @staticmethod
    def get_fields() -> dict[str, FieldInfo]:
        return {field.value.internal_name: field.value for field in UnitField}


# ---------------------------------------------------------------------------
# Customers
# ---------------------------------------------------------------------------
class CustomerField(Enum):
    CUSTOMER_ID = FieldInfo(
        'customerID', 'ID',
        type=FieldType.INT,
        required=True,
        is_primary_key=True,
        placeholder='Autogenerated ID'
    )
    FIRST_NAME = FieldInfo(
        'firstName', 'First Name',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. Juan',
        max_length=50,
    )
    LAST_NAME = FieldInfo(
        'lastName', 'Last Name',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. Dela Cruz',
        max_length=50,
    )
    PHONE_NUMBER = FieldInfo(
        'phoneNumber', 'Phone Number',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. 09123456789',
        max_length=11,
    )
    EMAIL_ADDRESS = FieldInfo(
        'emailAddress', 'Email Address',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. juan@example.com',
        max_length=100,
    )
    HOME_ADDRESS = FieldInfo(
        'homeAddress', 'Home Address',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. 123 Main St',
        max_length=255,
    )
    PROFILE_PICTURE = FieldInfo(
        'profilePicture', 'Profile Picture',
        type=FieldType.FILE,
        required=False,
        max_length=255,
    )
    DRIVER_LICENSE_ID = FieldInfo(
        'driverLicenseID', 'Driver License ID',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. D02-24-123456',
        max_length=15,
    )
    DRIVER_LICENSE_PICTURE = FieldInfo(
        'driverLicenseIDPicture', 'Driver License Picture',
        type=FieldType.FILE,
        required=True,
        max_length=255,
    )
    DRIVER_LICENSE_EXPIRY_DATE = FieldInfo(
        'driverLicenseExpiryDate', 'License Expiry Date',
        type=FieldType.DATE,
        required=True,
        placeholder='YYYY-MM-DD',
    )
    CUSTOMER_STATUS = FieldInfo(
        'customerStatus', 'Status',
        type=FieldType.SELECT,
        required=True,
        options=CUSTOMER_STATUS_OPTIONS,
        editable_in_add=False,   # defaults to 'Active' on insert
        editable_in_edit=True,   # user can toggle Active <-> Blacklisted
    )
    DATE_REGISTERED = FieldInfo(
        'dateRegistered', 'Date Registered',
        type=FieldType.DATE,
        required=True,
        placeholder='YYYY-MM-DD',
        auto_fill='today',
    )

    @staticmethod
    def from_internal_name(name: str) -> 'CustomerField':
        for field in CustomerField:
            if field.value.internal_name == name:
                return field
        raise ValueError(f'Unknown field: {name}')

    @staticmethod
    def get_fields() -> dict[str, FieldInfo]:
        return {field.value.internal_name: field.value for field in CustomerField}


# ---------------------------------------------------------------------------
# Rents
# ---------------------------------------------------------------------------
class RentField(Enum):
    RENT_ID = FieldInfo(
        'rentID', 'ID',
        type=FieldType.INT,
        required=True,
        is_primary_key=True,
        placeholder='Autogenerated ID'
    )
    CUSTOMER_ID = FieldInfo(
        'customerID', 'Customer',
        type=FieldType.INT,
        required=True,
        is_foreign_key=True,
        placeholder='Select a customer',
        dynamic_source='eligibleCustomers',  # Active customers only
        editable_in_edit=False,  # locked after creation
    )
    UNIT_ID = FieldInfo(
        'unitID', 'Unit',
        type=FieldType.INT,
        required=True,
        is_foreign_key=True,
        placeholder='Select a unit',
        dynamic_source='availableUnits',     # Available units only
        editable_in_edit=False,  # locked after creation
    )
    RENT_STATUS = FieldInfo(
        'rentStatus', 'Status',
        type=FieldType.SELECT,
        required=True,
        options=RENT_STATUS_OPTIONS,
        editable_in_add=False,   # system sets to 'Ongoing' on creation
        editable_in_edit=False,  # system-managed (closes on return)
    )
    RENT_DATETIME = FieldInfo(
        'rentDateTime', 'Rent Date & Time',
        type=FieldType.DATETIME,
        required=True,
        placeholder='YYYY-MM-DD HH:MM:SS',
        auto_fill='now',
        editable_in_edit=False,  # locked after creation
    )
    EXPECTED_RETURN_DATETIME = FieldInfo(
        'expectedReturnDateTime', 'Expected Return Date & Time',
        type=FieldType.DATETIME,
        required=True,
        placeholder='YYYY-MM-DD HH:MM:SS',
        editable_in_edit=False,  # locked after creation
    )
    ACTUAL_RETURN_DATETIME = FieldInfo(
        'actualReturnDateTime', 'Actual Return Date & Time',
        type=FieldType.DATETIME,
        required=False,
        placeholder='YYYY-MM-DD HH:MM:SS',
        editable_in_add=False,   # hidden on Add; filled when unit is returned
    )
    RENT_FEE = FieldInfo(
        'rentFee', 'Rent Fee (₱)',
        type=FieldType.REAL,
        required=True,
        placeholder='Auto-calculated',
        editable_in_add=False,   # auto-calculated: dailyRate × days
        editable_in_edit=False,  # immutable after creation
    )

    @staticmethod
    def from_internal_name(name: str) -> 'RentField':
        for field in RentField:
            if field.value.internal_name == name:
                return field
        raise ValueError(f'Unknown field: {name}')

    @staticmethod
    def get_fields() -> dict[str, FieldInfo]:
        return {field.value.internal_name: field.value for field in RentField}


# ---------------------------------------------------------------------------
# Liabilities
# ---------------------------------------------------------------------------
class LiabilityField(Enum):
    LIABILITY_ID = FieldInfo(
        'liabilityID', 'ID',
        type=FieldType.INT,
        required=True,
        is_primary_key=True,
        placeholder='Autogenerated ID'
    )
    CUSTOMER_ID = FieldInfo(
        'customerID', 'Customer',
        type=FieldType.INT,
        required=True,
        is_foreign_key=True,
        placeholder='Select a customer',
        # All customers except those who already have a Pending liability
        dynamic_source='customersWithoutPendingLiability',
        editable_in_edit=False,  # locked after creation
    )
    LIABILITY_DESCRIPTION = FieldInfo(
        'liabilityDescription', 'Description',
        type=FieldType.TEXT,
        required=True,
        placeholder='e.g. Broken side mirror',
        max_length=255,
    )
    LIABILITY_FEE = FieldInfo(
        'liabilityFee', 'Liability Fee (₱)',
        type=FieldType.REAL,
        required=True,
        placeholder='e.g. 500.0',
        editable_in_edit=False,  # locked after creation
    )
    LIABILITY_STATUS = FieldInfo(
        'liabilityStatus', 'Status',
        type=FieldType.SELECT,
        required=True,
        options=LIABILITY_STATUS_OPTIONS,
        editable_in_add=False,   # defaults to 'Pending' on creation
        editable_in_edit=True,   # user can mark as Settled
    )
    ISSUED_DATETIME = FieldInfo(
        'issuedDateTime', 'Issued Date & Time',
        type=FieldType.DATETIME,
        required=True,
        placeholder='YYYY-MM-DD HH:MM:SS',
        auto_fill='now',
    )

    @staticmethod
    def from_internal_name(name: str) -> 'LiabilityField':
        for field in LiabilityField:
            if field.value.internal_name == name:
                return field
        raise ValueError(f'Unknown field: {name}')

    @staticmethod
    def get_fields() -> dict[str, FieldInfo]:
        return {field.value.internal_name: field.value for field in LiabilityField}


# ---------------------------------------------------------------------------
# Payments
# ---------------------------------------------------------------------------
class PaymentField(Enum):
    PAYMENT_ID = FieldInfo(
        'paymentID', 'ID',
        type=FieldType.INT,
        required=True,
        is_primary_key=True,
        placeholder='Autogenerated ID'
    )
    CUSTOMER_ID = FieldInfo(
        'customerID', 'Customer',
        type=FieldType.INT,
        required=True,
        is_foreign_key=True,
        placeholder='Select a customer',
        dynamic_source='allCustomers',  # all customers regardless of status
        editable_in_edit=False,
    )
    LIABILITY_ID = FieldInfo(
        'liabilityID', 'Liability',
        type=FieldType.INT,
        required=False,
        is_foreign_key=True,
        placeholder='Select a liability (optional)',
        # Populated dynamically after customerID is selected:
        # shows Pending liabilities linked to the chosen customer.
        # Null when the payment covers a rent instead of a liability.
        dynamic_source='pendingLiabilitiesByCustomer',
        editable_in_edit=False,
    )
    PAID_AMOUNT = FieldInfo(
        'paidAmount', 'Paid Amount (₱)',
        type=FieldType.REAL,
        required=True,
        placeholder='e.g. 300.0',
    )
    PAYMENT_DATETIME = FieldInfo(
        'paymentDateTime', 'Payment Date & Time',
        type=FieldType.DATETIME,
        required=True,
        placeholder='YYYY-MM-DD HH:MM:SS',
        auto_fill='now',
    )

    @staticmethod
    def from_internal_name(name: str) -> 'PaymentField':
        for field in PaymentField:
            if field.value.internal_name == name:
                return field
        raise ValueError(f'Unknown field: {name}')

    @staticmethod
    def get_fields() -> dict[str, FieldInfo]:
        return {field.value.internal_name: field.value for field in PaymentField}


# ---------------------------------------------------------------------------
# Registry helpers
# ---------------------------------------------------------------------------
ENTITY_ENUM_MAP = {
    'unit':      UnitField,
    'customer':  CustomerField,
    'rent':      RentField,
    'liability': LiabilityField,
    'payment':   PaymentField,
}

def get_entity_schema_map():
    return {
        entity_name: [field.value.to_dict() for field in enum_class]
        for entity_name, enum_class in ENTITY_ENUM_MAP.items()
    }

def get_filtered_fields(entity_name: Optional[str] = None, return_attr: Optional[str] = None, **filters) -> List[Any]:
    """
    Filters FieldInfo objects based on their attributes.

    Args:
        entity_name: 'unit' | 'customer' | 'rent' | 'liability' | 'payment'.
                     None searches across all entities.
        return_attr: A specific FieldInfo attribute to return (e.g. 'internal_name').
                     None returns the full FieldInfo object.
        **filters:   Key-value pairs matching FieldInfo attributes.
    """
    enums_to_search = []
    if entity_name:
        if entity_name not in ENTITY_ENUM_MAP:
            raise ValueError(f'Unknown entity: {entity_name}')
        enums_to_search.append(ENTITY_ENUM_MAP[entity_name])
    else:
        enums_to_search = list(ENTITY_ENUM_MAP.values())

    results = []
    for entity_enum in enums_to_search:
        for field in entity_enum:
            field_info: FieldInfo = field.value
            match = all(
                hasattr(field_info, k) and getattr(field_info, k) == v
                for k, v in filters.items()
            )
            if match:
                results.append(getattr(field_info, return_attr) if return_attr else field_info)

    return results